// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        string        `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Data      string        `json:"data"`
	ExpiresAt time.Time     `json:"expires_at"`
	CreatedAt time.Time     `json:"created_at"`
}

type User struct {
	ID                uuid.UUID      `json:"id"`
	Email             string         `json:"email"`
	Password          string         `json:"password"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	VerificationToken sql.NullString `json:"verification_token"`
	VerifiedAt        sql.NullTime   `json:"verified_at"`
	TokenExpiry       sql.NullTime   `json:"token_expiry"`
	Role              string         `json:"role"`
}
