// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserExists(ctx context.Context, lower string) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	VerifyUser(ctx context.Context, arg VerifyUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
